version: "3"
services:
  web_service:
    build: ./web_service
    container_name: web_service
    image: hubspot/web_service
    #context: ./server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./web_service:/usr/app
      - /usr/app/node_modules
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - mongo
  hubspot_service:
    build: ./hubspot_service
    container_name: hubspot_service
    image: hubspot/hubspot_service
    #context: ./server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./hubspot_service:/usr/app
      - /usr/app/node_modules
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - mongo
  client:
    build: ./client
    container_name: idea_tracker_client
    image: hubspot/idea_tracker_client
    # command: tail -F anything
    command: yarn start
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    depends_on:
      - web_service
    ports:
      - "3000:3000"
    env_file: ./.env

  mongo:
    # upgrade to https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3 later
    image: mongo
    container_name: idea_tracker_database
    volumes:
      - ./mongo-volume:/data/db
    expose:
      - "27017"

  mongo_express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./.env
volumes:
  web_service:
  hubspot_service:
  client:
  mongo:
